import re
from typing import List

def readMol2Input(mol2_input_path:str) -> List[str]:
    """
    Extracts atomic symbols and 3D coordinates from the @<TRIPOS>ATOM section of a .mol2 file.

    :param mol2_input_path: (str) Path to the .mol2 file.
    :return: (list) A list of lists, each containing an atom symbol and its x, y, z coordinates.
    """
    coords = []
    with open(mol2_input_path, 'r') as f:
        lines = f.readlines()
        atom_section = False
        for line in lines:
            if line.startswith("@<TRIPOS>ATOM"):
                atom_section = True
                continue
            elif line.startswith("@<TRIPOS>"):
                atom_section = False
            if atom_section:
                parts = line.split()
                if len(parts) >= 6:
                    raw_atom = parts[1] # Remove digits from atom name
                    atom = re.sub(r"\d+", "", raw_atom)
                    x, y, z = map(float, parts[2:5])
                    coords.append([atom, x, y, z])
    return coords

def write_xyz_file(atom_list: List[str], xyz_file_path: str, comment:str ="Generated by write_xyz_file")->None:
    """
    Writes an XYZ file from a list of [atom, x, y, z] entries.

    :param atom_list: List of lists, each like ['C', x, y, z]
    :param xyz_file_path: Output file path
    :param comment: Optional comment line for the XYZ file
    """
    num_atoms = len(atom_list)

    with open(xyz_file_path, 'w') as f:
        # Line 1: number of atoms
        f.write(f"{num_atoms}\n")

        # Line 2: comment
        f.write(f"{comment}\n")

        # Lines 3+: atom coordinates
        for atom, x, y, z in atom_list:
            f.write(f"{atom:2s}  {x: .6f}  {y: .6f}  {z: .6f}\n")


# molecules_to_add = [
#     "taxol", "geosmin", "absicic-acid", "cholesterol", "retinol", "testosterone", "estradiol", "cortisone", 
#     "progesterone", "vitamin-b1", "vitamin-d2", "vitamin-d3", "b-carotene", "squalene", "zeaxanthin", "phytol", 
#     "geranylgeraniol", "lanosterol", "stearidonic-acid", "Eicosatetraenoic-acid", "Eicosapentaenoic-acid",
#     "riboflavin", "fad", "folic-acid", "tribenzylamine"
# ]

benchmark_path = "C:\\Users\\User\\G2B\\Gaussian-2-Blender\\input_examples\\benchmarking2\\"

molecule_name = "propionitrile"
input_path = benchmark_path + molecule_name + ".mol2"
output_path = benchmark_path + molecule_name + ".xyz"
mol2_file = readMol2Input(input_path)
xyz_file = write_xyz_file(mol2_file, output_path)

# for molecule in molecules_to_add:
#     i = benchmark_path + molecule + ".mol2"
#     o = benchmark_path + molecule + ".xyz"
#     f = readMol2Input(i)
#     x = write_xyz_file(f, o)

